### ISSUE TITLE
Need to support https services

### ISSUE THREAD

**Issue by wa5i** [Tongsuo-Project/RustyVault#27]

**Comment by InfoHunter** [comment]
No. This is not the goal of RustyVault. It should have one cryptography abstract layer, so that RustyVault can use different underlying crypto/tls libraries like OpenSSL, Tongsuo, ring, Rustls...

**Comment by InfoHunter** [comment]
Currently implementation in `barrier_aes_gcm` needs a refactor since it binds to OpenSSL API style *only*. It should use a different general API when the cryptography abstract layer is ready (which is I mentioned in previous comment)

**Comment by wa5i** [comment]
I'm developing
